// Curated vocabulary list for the daily email's "Words of the Day" section.
// Deliberately large and spread across domains so daily picks (1 featured +
// 4 bonus) don't visibly repeat for many months. Add more entries any time —
// the picker just indexes by day-of-year, so growing the list only helps.

export interface WordEntry {
  word: string;
  definition: string;
  example: string;
  category: string;
}

export const WORDS: WordEntry[] = [
  // General / elevated vocabulary
  { word: "ephemeral", definition: "lasting for a very short time", example: "The cherry blossoms are ephemeral, gone within a week of blooming.", category: "general" },
  { word: "ubiquitous", definition: "present, appearing, or found everywhere", example: "Smartphones have become ubiquitous in modern life.", category: "general" },
  { word: "cogent", definition: "clear, logical, and convincing", example: "She made a cogent argument for postponing the launch.", category: "general" },
  { word: "pragmatic", definition: "dealing with things sensibly and realistically", example: "He took a pragmatic approach to fixing the budget shortfall.", category: "general" },
  { word: "ambivalent", definition: "having mixed feelings or contradictory ideas about something", example: "I'm ambivalent about moving cities — excited but also nervous.", category: "general" },
  { word: "candor", definition: "the quality of being open and honest in expression", example: "I appreciated her candor when she told me the plan wouldn't work.", category: "general" },
  { word: "meticulous", definition: "showing great attention to detail; very careful and precise", example: "The watchmaker was meticulous about every tiny gear.", category: "general" },
  { word: "resilient", definition: "able to withstand or recover quickly from difficult conditions", example: "The local economy proved resilient after the factory closed.", category: "general" },
  { word: "nuanced", definition: "characterized by subtle shades of meaning or expression", example: "Her review offered a nuanced take on a divisive film.", category: "general" },
  { word: "vindicate", definition: "to clear someone of blame or suspicion", example: "New evidence eventually vindicated the accused employee.", category: "general" },
  { word: "conundrum", definition: "a confusing and difficult problem or question", example: "Choosing between two great job offers was a pleasant conundrum.", category: "general" },
  { word: "esoteric", definition: "intended for or understood by only a small group with specialized knowledge", example: "The lecture drifted into esoteric mathematics few could follow.", category: "general" },
  { word: "gregarious", definition: "fond of company; sociable", example: "Her gregarious personality made her the center of every party.", category: "general" },
  { word: "myriad", definition: "a countless or extremely great number", example: "There are myriad ways to solve this problem.", category: "general" },
  { word: "obfuscate", definition: "to deliberately make something unclear or confusing", example: "The report seemed designed to obfuscate the real cost overruns.", category: "general" },
  { word: "quintessential", definition: "representing the most perfect or typical example of something", example: "The little bistro felt like the quintessential Parisian café.", category: "general" },
  { word: "sycophant", definition: "a person who acts obsequiously toward someone to gain advantage", example: "He was surrounded by sycophants who never questioned his ideas.", category: "general" },
  { word: "tenacious", definition: "persisting firmly, not easily stopped or discouraged", example: "Her tenacious pursuit of the story eventually broke the case open.", category: "general" },
  { word: "unequivocal", definition: "leaving no doubt; unambiguous", example: "The board gave an unequivocal yes to the merger.", category: "general" },
  { word: "vicarious", definition: "experienced through the feelings or actions of another person", example: "He got a vicarious thrill watching his daughter's first race.", category: "general" },
  { word: "zealous", definition: "having or showing great energy or enthusiasm for a cause", example: "The new hire was zealous about improving the onboarding process.", category: "general" },
  { word: "arbitrary", definition: "based on random choice rather than reason or system", example: "The cutoff score felt arbitrary and unrelated to actual skill.", category: "general" },
  { word: "coalesce", definition: "to come together to form one mass or whole", example: "The scattered protests slowly coalesced into a single movement.", category: "general" },
  { word: "deference", definition: "humble submission and respect shown to another", example: "The interns spoke with deference to the senior partners.", category: "general" },
  { word: "equanimity", definition: "mental calmness and composure, especially in a difficult situation", example: "She handled the layoff news with surprising equanimity.", category: "general" },
  { word: "fastidious", definition: "very attentive to and concerned about accuracy and detail", example: "He was fastidious about labeling every cable in the server room.", category: "general" },
  { word: "garrulous", definition: "excessively talkative, especially about trivial matters", example: "The garrulous cab driver talked the entire ride.", category: "general" },
  { word: "hackneyed", definition: "lacking originality or freshness; overused", example: "The movie leaned on hackneyed plot twists.", category: "general" },
  { word: "impetuous", definition: "acting quickly without thought or care", example: "Buying the car on a whim was an impetuous decision.", category: "general" },
  { word: "juxtapose", definition: "to place close together for contrasting effect", example: "The exhibit juxtaposes old photographs with modern skyline shots.", category: "general" },

  // Food & culinary
  { word: "umami", definition: "a savory taste imparted by glutamate, one of the five basic tastes", example: "Soy sauce adds a deep umami flavor to the broth.", category: "food" },
  { word: "mise en place", definition: "the practice of organizing and arranging ingredients before cooking", example: "Good mise en place makes the actual cooking go smoothly.", category: "food" },
  { word: "deglaze", definition: "to add liquid to a pan to loosen browned food bits after sautéing", example: "Deglaze the pan with white wine to make the sauce.", category: "food" },
  { word: "emulsify", definition: "to combine two liquids that don't normally mix, like oil and water", example: "Whisk quickly to emulsify the oil into the egg yolk for mayonnaise.", category: "food" },
  { word: "terroir", definition: "the complete natural environment that gives a food or wine its character", example: "The wine's earthy notes reflect the region's distinct terroir.", category: "food" },
  { word: "braise", definition: "to cook food slowly in a small amount of liquid after searing", example: "Braise the short ribs for three hours until tender.", category: "food" },
  { word: "julienne", definition: "to cut vegetables into long, thin strips", example: "Julienne the carrots for the stir-fry.", category: "food" },
  { word: "confit", definition: "food, typically meat, slow-cooked and preserved in its own fat", example: "Duck confit is rich and falls off the bone.", category: "food" },
  { word: "brunoise", definition: "a finely diced mixture of vegetables, usually under 3mm cubes", example: "A brunoise of celery, carrot, and onion forms the soup's base.", category: "food" },
  { word: "al dente", definition: "cooked so as to still be firm when bitten, typically of pasta", example: "Boil the pasta until al dente, about nine minutes.", category: "food" },
  { word: "charcuterie", definition: "cold cooked or cured meats, or the art of preparing them", example: "The charcuterie board had prosciutto, salami, and pâté.", category: "food" },
  { word: "roux", definition: "a mixture of fat and flour used to thicken sauces", example: "Whisk the roux constantly so it doesn't burn.", category: "food" },
  { word: "sous vide", definition: "cooking food slowly in a sealed bag in temperature-controlled water", example: "The steak was cooked sous vide for perfectly even doneness.", category: "food" },
  { word: "fermentation", definition: "the chemical breakdown of a substance by bacteria, yeasts, or microorganisms", example: "Fermentation gives kimchi its tangy, sour flavor.", category: "food" },
  { word: "zest", definition: "the outer, colored part of citrus peel used for flavoring", example: "Add lemon zest to brighten up the cake batter.", category: "food" },
  { word: "caramelize", definition: "to heat sugar until it browns and develops a rich flavor", example: "Let the onions caramelize slowly over low heat for sweetness.", category: "food" },
  { word: "marbling", definition: "the streaks of fat within a cut of meat", example: "The steak's heavy marbling made it especially tender.", category: "food" },
  { word: "reduction", definition: "a sauce thickened and concentrated by simmering off liquid", example: "Drizzle the balsamic reduction over the roasted vegetables.", category: "food" },
  { word: "proof", definition: "to let bread dough rise before baking", example: "Let the dough proof for an hour in a warm spot.", category: "food" },
  { word: "piquant", definition: "having a pleasantly sharp or spicy taste", example: "The mustard sauce had a piquant kick.", category: "food" },

  // Finance & business
  { word: "amortize", definition: "to gradually pay off a debt over time through regular payments", example: "The loan is amortized over 30 years.", category: "finance" },
  { word: "liquidity", definition: "the availability of liquid assets to a company or market", example: "The company kept extra cash on hand to maintain liquidity.", category: "finance" },
  { word: "arbitrage", definition: "profiting from price differences of the same asset in different markets", example: "Traders used arbitrage to profit from the currency mismatch.", category: "finance" },
  { word: "solvency", definition: "the ability of a company to meet its long-term financial obligations", example: "Auditors questioned the firm's solvency after the losses.", category: "finance" },
  { word: "collateral", definition: "an asset pledged as security for repayment of a loan", example: "She put up her house as collateral for the business loan.", category: "finance" },
  { word: "diversification", definition: "spreading investments to reduce exposure to any single risk", example: "Diversification across sectors softened the portfolio's losses.", category: "finance" },
  { word: "equity", definition: "ownership interest in an asset after debts are subtracted", example: "The founders retained 60% equity after the funding round.", category: "finance" },
  { word: "volatility", definition: "the degree of variation in a trading price over time", example: "The stock's volatility scared off cautious investors.", category: "finance" },
  { word: "depreciation", definition: "a reduction in the value of an asset over time", example: "The car's depreciation was steepest in its first year.", category: "finance" },
  { word: "leverage", definition: "using borrowed capital to increase the potential return of an investment", example: "The firm used leverage to fund the acquisition.", category: "finance" },
  { word: "escrow", definition: "money held by a third party until conditions of an agreement are met", example: "The deposit sat in escrow until closing day.", category: "finance" },
  { word: "dividend", definition: "a payment made by a company to its shareholders from profits", example: "The company raised its dividend for the tenth straight year.", category: "finance" },
  { word: "underwrite", definition: "to accept financial responsibility for a risk in exchange for a fee", example: "The bank agreed to underwrite the new bond issue.", category: "finance" },
  { word: "hedge", definition: "an investment made to reduce the risk of adverse price movements", example: "They bought options as a hedge against currency swings.", category: "finance" },
  { word: "accrual", definition: "an accounting method recognizing revenue/expenses when incurred, not when paid", example: "Under accrual accounting, the sale is recorded before the cash arrives.", category: "finance" },
  { word: "fiduciary", definition: "a person or entity legally obligated to act in another's best interest", example: "As a fiduciary, the advisor had to prioritize the client's returns.", category: "finance" },
  { word: "amortization", definition: "the process of writing off an intangible asset's cost over time", example: "Amortization of the patent reduced reported profits each year.", category: "finance" },
  { word: "recession", definition: "a period of temporary economic decline with reduced trade and activity", example: "Hiring slowed sharply as the recession deepened.", category: "finance" },
  { word: "capitulation", definition: "a point of mass surrender in markets, often marking a price bottom", example: "Analysts called the sharp sell-off a sign of capitulation.", category: "finance" },
  { word: "principal", definition: "the original sum of money invested or loaned, before interest", example: "Extra payments went straight toward the loan's principal.", category: "finance" },

  // Healthcare & medicine
  { word: "prognosis", definition: "a forecast of the likely course of a disease or ailment", example: "The doctor gave a cautiously optimistic prognosis.", category: "healthcare" },
  { word: "etiology", definition: "the cause or origin of a disease or condition", example: "The etiology of the outbreak was traced to contaminated water.", category: "healthcare" },
  { word: "contraindicated", definition: "advised against for a specific person or condition, e.g. a treatment", example: "The medication is contraindicated for patients with liver disease.", category: "healthcare" },
  { word: "asymptomatic", definition: "showing no symptoms of a disease despite being infected", example: "Many carriers of the virus were entirely asymptomatic.", category: "healthcare" },
  { word: "acute", definition: "of sudden onset and typically brief and severe, of a condition", example: "He was admitted for acute appendicitis.", category: "healthcare" },
  { word: "chronic", definition: "persisting for a long time or constantly recurring, of a condition", example: "She manages her chronic back pain with physical therapy.", category: "healthcare" },
  { word: "palliative", definition: "relieving symptoms without curing the underlying condition", example: "The hospice offered palliative care to keep him comfortable.", category: "healthcare" },
  { word: "comorbidity", definition: "the simultaneous presence of two or more diseases in a patient", example: "Diabetes was a common comorbidity among the study's patients.", category: "healthcare" },
  { word: "idiopathic", definition: "relating to a disease with no identifiable cause", example: "Her condition was classified as idiopathic after extensive testing.", category: "healthcare" },
  { word: "malignant", definition: "cancerous and tending to spread or worsen", example: "The biopsy confirmed the tumor was malignant.", category: "healthcare" },
  { word: "benign", definition: "not harmful, especially of a tumor that is not cancerous", example: "Thankfully, the growth turned out to be benign.", category: "healthcare" },
  { word: "titrate", definition: "to gradually adjust a drug dose to find the optimal amount", example: "The doctor titrated the dosage over several weeks.", category: "healthcare" },
  { word: "prophylactic", definition: "intended to prevent disease", example: "She took a prophylactic antibiotic before the dental surgery.", category: "healthcare" },
  { word: "sedentary", definition: "characterized by much sitting and little physical activity", example: "A sedentary lifestyle raises the risk of heart disease.", category: "healthcare" },
  { word: "triage", definition: "the process of prioritizing patients by urgency of need", example: "Nurses triaged incoming patients in order of severity.", category: "healthcare" },
  { word: "remission", definition: "a period during which symptoms of a disease are reduced or absent", example: "The cancer has been in remission for two years.", category: "healthcare" },
  { word: "vasodilation", definition: "the widening of blood vessels, which lowers blood pressure", example: "The medication works by causing vasodilation.", category: "healthcare" },
  { word: "inflammation", definition: "a localized physical condition where part of the body becomes swollen and painful", example: "Ice helps reduce inflammation around the joint.", category: "healthcare" },
  { word: "epidemiology", definition: "the branch of medicine studying the causes and spread of disease", example: "Epidemiology helped pinpoint the outbreak's source.", category: "healthcare" },
  { word: "subcutaneous", definition: "situated or introduced under the skin", example: "Insulin is typically given as a subcutaneous injection.", category: "healthcare" },

  // Sports
  { word: "attrition", definition: "gradual wearing down of an opponent's strength or resolve", example: "The marathon became a war of attrition in the final miles.", category: "sports" },
  { word: "parity", definition: "a state of equality or equivalence between competitors", example: "The new salary cap brought more parity to the league.", category: "sports" },
  { word: "clutch", definition: "performing well under pressure, especially at a critical moment", example: "Her clutch free throws sealed the win.", category: "sports" },
  { word: "dynasty", definition: "a team or program that dominates its sport over an extended period", example: "The team built a dynasty with three championships in a row.", category: "sports" },
  { word: "rebuild", definition: "a team's strategy of trading veterans for young talent to improve long-term", example: "The franchise began a full rebuild after a losing season.", category: "sports" },
  { word: "momentum", definition: "the strength or force gained by a team's motion or successive events", example: "The comeback win gave the team huge momentum heading into playoffs.", category: "sports" },
  { word: "veteran", definition: "a player with long experience in a particular sport", example: "The veteran quarterback mentored the rookies all season.", category: "sports" },
  { word: "underdog", definition: "a competitor thought to have little chance of winning", example: "The underdog upset the top seed in the first round.", category: "sports" },
  { word: "tactical", definition: "relating to carefully planned actions to achieve a specific goal", example: "The coach made a tactical substitution to shore up defense.", category: "sports" },
  { word: "endurance", definition: "the ability to sustain prolonged physical or mental effort", example: "Distance runners train for years to build endurance.", category: "sports" },
  { word: "formidable", definition: "inspiring fear or respect through being impressively powerful or capable", example: "The defending champions remain a formidable opponent.", category: "sports" },
  { word: "handicap", definition: "a disadvantage given to a stronger competitor to level the field", example: "His golf handicap dropped five strokes this year.", category: "sports" },
  { word: "stalemate", definition: "a situation in which neither side can gain an advantage", example: "The two heavyweights fought to a defensive stalemate.", category: "sports" },
  { word: "prodigy", definition: "a young person with exceptional talent or ability", example: "The 16-year-old chess prodigy beat three grandmasters this year.", category: "sports" },
  { word: "adrenaline", definition: "a hormone that increases heart rate and energy, associated with excitement", example: "The crowd's roar gave the runners an adrenaline boost.", category: "sports" },

  // Science & technology
  { word: "heuristic", definition: "a practical method or shortcut for solving a problem quickly", example: "The chess engine uses a heuristic to evaluate positions fast.", category: "science" },
  { word: "latency", definition: "the delay before a transfer of data begins after an instruction", example: "The video call suffered from high latency.", category: "science" },
  { word: "entropy", definition: "a measure of disorder or randomness in a system", example: "Without maintenance, entropy in the old system kept increasing.", category: "science" },
  { word: "algorithm", definition: "a step-by-step procedure for solving a problem or performing a computation", example: "The recommendation algorithm learns from your viewing habits.", category: "science" },
  { word: "redundancy", definition: "the inclusion of extra components to ensure reliability if one fails", example: "The spacecraft had triple redundancy on its critical systems.", category: "science" },
  { word: "asymptote", definition: "a line a curve approaches but never quite touches", example: "The graph's growth rate flattens toward an asymptote.", category: "science" },
  { word: "catalyst", definition: "a substance that speeds up a chemical reaction without being consumed", example: "The enzyme acts as a catalyst in digestion.", category: "science" },
  { word: "quantum", definition: "the smallest discrete unit of a physical property", example: "Quantum computers use qubits instead of classical bits.", category: "science" },
  { word: "encryption", definition: "the process of converting information into a code to prevent unauthorized access", example: "All messages are protected with end-to-end encryption.", category: "science" },
  { word: "scalable", definition: "able to be expanded or increased in size or capacity", example: "The startup needed a more scalable database architecture.", category: "science" },
  { word: "synthesis", definition: "the combination of components to form a connected whole", example: "Photosynthesis is the synthesis of sugars from sunlight and CO2.", category: "science" },
  { word: "empirical", definition: "based on observation or experiment rather than theory alone", example: "The claim lacked empirical evidence to back it up.", category: "science" },
  { word: "iteration", definition: "one repetition of a process, often refining the result each time", example: "The design went through a dozen iterations before launch.", category: "science" },
  { word: "obsolescence", definition: "the process of becoming outdated or no longer used", example: "Planned obsolescence keeps consumers buying new devices.", category: "science" },
  { word: "bandwidth", definition: "the maximum rate of data transfer across a network", example: "Streaming video in 4K requires a lot of bandwidth.", category: "science" },
  { word: "anomaly", definition: "something that deviates from what is standard or expected", example: "The telescope detected a strange anomaly in the star's brightness.", category: "science" },
  { word: "biomimicry", definition: "designing systems modeled on biological processes found in nature", example: "The building's cooling system uses biomimicry inspired by termite mounds.", category: "science" },
  { word: "singularity", definition: "a hypothetical point where technological growth becomes uncontrollable and irreversible", example: "Some researchers debate how close we are to a technological singularity.", category: "science" },
  { word: "throughput", definition: "the amount of material or items passing through a system in a given time", example: "The new server doubled the app's throughput.", category: "science" },
  { word: "interoperability", definition: "the ability of different systems to work together and exchange information", example: "Poor interoperability between the two platforms slowed the migration.", category: "science" },

  // Arts & literature
  { word: "allegory", definition: "a story, poem, or picture with a hidden moral or political meaning", example: "The novel works as an allegory for the rise of authoritarianism.", category: "arts" },
  { word: "juxtaposition", definition: "the placement of two things close together for contrasting effect", example: "The film's juxtaposition of wealth and poverty is jarring.", category: "arts" },
  { word: "motif", definition: "a recurring element or theme within an artistic work", example: "Water is a recurring motif throughout the poet's collection.", category: "arts" },
  { word: "satire", definition: "the use of humor or exaggeration to criticize people's vices or society", example: "The show is a sharp satire of corporate culture.", category: "arts" },
  { word: "verisimilitude", definition: "the appearance of being true or real", example: "The director insisted on verisimilitude, filming on real city streets.", category: "arts" },
  { word: "pathos", definition: "a quality that evokes pity or sadness in a work of art", example: "The final scene relies heavily on pathos to land its ending.", category: "arts" },
  { word: "avant-garde", definition: "new and experimental ideas, especially in the arts", example: "The gallery specializes in avant-garde installation art.", category: "arts" },
  { word: "denouement", definition: "the final resolution of the strands of a story's plot", example: "The novel's denouement ties up every subplot neatly.", category: "arts" },
  { word: "leitmotif", definition: "a recurring musical theme associated with a person, idea, or situation", example: "The villain's leitmotif plays every time he appears.", category: "arts" },
  { word: "vernacular", definition: "the language or dialect spoken by ordinary people in a region", example: "The playwright wrote dialogue in the local vernacular.", category: "arts" },
  { word: "pastiche", definition: "a work that imitates the style of another artist or period", example: "The album is a loving pastiche of 1970s soul music.", category: "arts" },
  { word: "chiaroscuro", definition: "the use of strong contrasts between light and dark in art", example: "Caravaggio was famous for his dramatic chiaroscuro.", category: "arts" },
  { word: "trope", definition: "a common or overused theme or device in art and literature", example: "The chosen-one trope shows up in countless fantasy novels.", category: "arts" },
  { word: "improvisation", definition: "the act of creating something spontaneously without preparation", example: "The jazz trio's set was almost entirely improvisation.", category: "arts" },
  { word: "narrative arc", definition: "the chronological progression of events in a story", example: "The show's narrative arc builds slowly across three seasons.", category: "arts" },

  // Law & government
  { word: "jurisdiction", definition: "the official power to make legal decisions and judgments", example: "The case fell outside the court's jurisdiction.", category: "law" },
  { word: "precedent", definition: "an earlier decision regarded as an example for later similar cases", example: "The ruling set an important precedent for privacy law.", category: "law" },
  { word: "litigation", definition: "the process of taking legal action through the courts", example: "The dispute ended in years of costly litigation.", category: "law" },
  { word: "statute", definition: "a written law passed by a legislative body", example: "The new statute raised the minimum wage statewide.", category: "law" },
  { word: "injunction", definition: "a court order requiring or forbidding a specific action", example: "The judge issued an injunction halting the demolition.", category: "law" },
  { word: "indict", definition: "to formally charge someone with a serious crime", example: "The grand jury voted to indict the former executive.", category: "law" },
  { word: "plaintiff", definition: "a person who brings a case against another in a court of law", example: "The plaintiff sought damages for breach of contract.", category: "law" },
  { word: "liability", definition: "the state of being legally responsible for something", example: "The company denied liability for the factory accident.", category: "law" },
  { word: "bipartisan", definition: "involving agreement or cooperation between two political parties", example: "The infrastructure bill passed with bipartisan support.", category: "law" },
  { word: "constituency", definition: "a body of voters in a specified area who elect a representative", example: "The senator held a town hall for her constituency.", category: "law" },
  { word: "sovereignty", definition: "supreme authority of a state to govern itself", example: "The treaty respected each nation's sovereignty.", category: "law" },
  { word: "amendment", definition: "a formal change or addition to a legal document or law", example: "The amendment expanded voting rights nationwide.", category: "law" },
  { word: "deposition", definition: "sworn out-of-court testimony used as evidence in a legal proceeding", example: "The witness gave a deposition before the trial began.", category: "law" },
  { word: "arbitration", definition: "the settling of a dispute by a neutral third party outside court", example: "The contract required arbitration instead of a lawsuit.", category: "law" },
  { word: "clemency", definition: "mercy shown by reducing or excusing a punishment", example: "The governor granted clemency to the aging inmate.", category: "law" },

  // Psychology & behavior
  { word: "cognitive dissonance", definition: "mental discomfort from holding two conflicting beliefs at once", example: "He felt cognitive dissonance buying the car after criticizing consumerism.", category: "psychology" },
  { word: "confirmation bias", definition: "the tendency to favor information that confirms existing beliefs", example: "Confirmation bias led her to only read articles she already agreed with.", category: "psychology" },
  { word: "empathy", definition: "the ability to understand and share the feelings of another", example: "Good managers lead with empathy, not just authority.", category: "psychology" },
  { word: "resilience", definition: "the capacity to recover quickly from difficulties", example: "Therapy helped him build resilience after the setback.", category: "psychology" },
  { word: "introspection", definition: "the examination of one's own thoughts and feelings", example: "A long walk gave her time for quiet introspection.", category: "psychology" },
  { word: "rumination", definition: "repeated, often negative thinking about the same problem", example: "Rumination over the mistake kept him up all night.", category: "psychology" },
  { word: "extrinsic motivation", definition: "motivation driven by external rewards rather than internal satisfaction", example: "The bonus was pure extrinsic motivation to hit the deadline.", category: "psychology" },
  { word: "placebo effect", definition: "a beneficial effect from a treatment that has no real therapeutic value", example: "Some patients improved from the sugar pill due to the placebo effect.", category: "psychology" },
  { word: "projection", definition: "attributing one's own feelings or traits to someone else", example: "His accusations said more about projection than about her.", category: "psychology" },
  { word: "assimilation", definition: "the process of adapting new information into existing understanding", example: "Cultural assimilation happened gradually over two generations.", category: "psychology" },
  { word: "gaslighting", definition: "manipulating someone into doubting their own perception of reality", example: "He accused his coworker of gaslighting him about the meeting time.", category: "psychology" },
  { word: "catharsis", definition: "the process of releasing strong or repressed emotions", example: "Writing the letter, even unsent, gave her a sense of catharsis.", category: "psychology" },
  { word: "imposter syndrome", definition: "persistent self-doubt about one's abilities despite evident success", example: "Even after the promotion, she battled imposter syndrome.", category: "psychology" },
  { word: "groupthink", definition: "the tendency for a group to make poor decisions to avoid conflict", example: "Groupthink led the committee to approve a flawed plan.", category: "psychology" },
  { word: "self-efficacy", definition: "one's belief in their own ability to succeed at a task", example: "Small early wins boosted the team's self-efficacy.", category: "psychology" },

  // Nature & environment
  { word: "biodiversity", definition: "the variety of plant and animal life in a particular habitat", example: "The rainforest holds an astonishing amount of biodiversity.", category: "nature" },
  { word: "ecosystem", definition: "a biological community of interacting organisms and their environment", example: "Coral reefs support one of the ocean's richest ecosystems.", category: "nature" },
  { word: "symbiosis", definition: "a mutually beneficial relationship between two different organisms", example: "The clownfish and anemone live in perfect symbiosis.", category: "nature" },
  { word: "migratory", definition: "relating to animals that move seasonally between regions", example: "The migratory birds return north every spring.", category: "nature" },
  { word: "sustainable", definition: "able to be maintained at a steady level without depleting resources", example: "The farm switched to more sustainable irrigation methods.", category: "nature" },
  { word: "erosion", definition: "the gradual wearing away of land by wind, water, or other forces", example: "Coastal erosion has shrunk the beach by ten feet a year.", category: "nature" },
  { word: "photosynthesis", definition: "the process by which plants convert sunlight into chemical energy", example: "Photosynthesis releases oxygen as a byproduct.", category: "nature" },
  { word: "biome", definition: "a large naturally occurring community of flora and fauna in a habitat", example: "The tundra biome supports surprisingly hardy wildlife.", category: "nature" },
  { word: "conservation", definition: "the protection and careful management of natural resources", example: "The reserve focuses on conservation of the region's wetlands.", category: "nature" },
  { word: "invasive species", definition: "a non-native organism that spreads and causes ecological harm", example: "The invasive species outcompeted native fish for food.", category: "nature" },
];
